[package]
name = "ssz-examples"
version = "0.0.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
libssz = { version = "0.3.0", path = "../crates/ssz" }
libssz-types = { version = "0.3.0", path = "../crates/ssz-types" }
libssz-merkle = { version = "0.3.0", path = "../crates/ssz-merkle" }

[[bin]]
name = "basic_types"
path = "src/bin/basic_types.rs"

[[bin]]
name = "containers"
path = "src/bin/containers.rs"

[[bin]]
name = "collections"
path = "src/bin/collections.rs"

[[bin]]
name = "no_std_usage"
path = "src/bin/no_std_usage.rs"
